In [4]:
#Author-Vishal Burman

### To begin with the majority of my undergraduate years have been spent in listening to the never-ending stupid arguments... Is TensorFlow better or Pytorch? I say is it too much if you try out those two as well as other libraries and see for yourself which one works for you best?

### So here I will be trying out Amazon's deep learning framework and I thought it will be really amazing if I document my learnings on the way so anyone viewing this notebook can be benefitted.
### Let's dive right into it...

In [5]:
#Import mxnet libraries and dependencies

In [6]:
import mxnet as mx
from mxnet import nd    #...Yep this much only to get started

In [ ]:
"""

ndarrays represent the fundamental structure of neural networks. ndarrays is most commonly called Tensors.
In deep learning tensors are pretty simple. Apparently if you are a physicist tensors become much more scary...
Well in deep learning it purely means an array...


"""

In [7]:
#Lets create a one-dimensional ndarray...This one's called a VECTOR

In [8]:
x=nd.arange(12)
x


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>

In [ ]:
"""
The output is pretty much intuitive MxNet creates a vector(array) of size 12 and the vector resides on CPU
We can shift to GPU but more on that later...Not the 0 parameter in CPU does not represent a specific core.

"""

In [9]:
#To get the shape pretty much the numpy equivalent:

In [11]:
x.shape

(12,)

In [12]:
#Another equivalent of your standard numpy implementation....to get the size of the array:

In [13]:
x.size

12

In [ ]:
"""

We use the reshape function to shape one(possibly multi-dimensional) array into another that contains the
same number of elements. So we can take our one-dimensional array and convert it into a 3x4 matrix. Like 
numpy MxNet provide a simple function .reshape((n, m))

"""

In [14]:
x=x.reshape((3, 4))
x


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [ ]:
"""

There is one other concept while reshaping a vector...I struggled with this for a really very long time.
Apparently there is a shortcut for reshaping which is the -1 concept. 
To explain this really intuitively...python is really lazy so is we want to reshape an ndarray we can supply
only one-dimension to it and the next parameter we can supplied -1 and MxNet calculates what is the next value.
Its a handy shortcut while working with large dimensions...

"""

In [15]:
x=x.reshape((3, 4))
x


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [16]:
#We reverse our x to original array and apply the -1 concept

In [17]:
x=nd.arange(12)
x=x.reshape((3, -1))
x


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [ ]:
"""

The empty function of MxNet pretty much grabs up some memory and hands us back a matrix without setting the
values of any of its entries. Pretty efficient but that also means it might hand us some arbitrary values...

"""

In [18]:
nd.empty((3, 4))


[[0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00]
 [0.000000e+00 0.000000e+00 4.820467e-43 0.000000e+00]
 [0.000000e+00 9.275518e-39 0.000000e+00 9.918363e-39]]
<NDArray 3x4 @cpu(0)>

In [ ]:
"""

Well we generally want our matrices initialized either with zeros, some known constant or numbers randomly
sampled from a known distribution.

"""

In [20]:
#TO create ndarray with values initialized to zeros:
nd.zeros((2, 3, 4))


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<NDArray 2x3x4 @cpu(0)>

In [21]:
#To create ndarrays(tensors) with each element set to one:
nd.ones((2, 3, 4))


[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
<NDArray 2x3x4 @cpu(0)>

In [25]:
#We can also supply our own values:
y=nd.array(([1, 2, 3], [4, 5, 6], [7, 8, 9]))
y


[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
<NDArray 3x3 @cpu(0)>

In [ ]:
"""

Moving to somewhat complex terms...If we want to create an ndarray according to some known probablity
distribution. This is especially common if we intend to use the array as a parameter in a neural network

"""

In [26]:
#In the following snippet the elements are randomly sampled in normal distribution with zero mean and unit variance

In [27]:
nd.random.normal(0, 1, shape=(3, 4))


[[ 1.1630785   0.4838046   0.29956347  0.15302546]
 [-1.1688148   1.5580711  -0.5459446  -2.3556297 ]
 [ 0.5414402   2.6785066   1.2546345  -0.54877394]]
<NDArray 3x4 @cpu(0)>

### Well the above are not exhaustive but its pretty much enough to give us an idea as to what are we dealing with

### Let's move onto operations on tensors(NDarrays)...

In [ ]:
"""

In MxNet the arithmetic operators like +, -, /, *, ** have been lifted to element-wise operations for identically
shaped tensors of arbitrary shape. We can call element-wise operations on any two tensors of the same shape, including
matrices.

"""

In [30]:
x=nd.array([1, 2, 4, 8])
y=nd.ones_like(x)*2  #This returns an array of ones...i multiplied it by two so basically its an array of 2's
print('x =', x)
print('x + y', x+y)
print('x - y', x-y)
print('x*y', x*y)
print('x / y', x/y)

x = 
[1. 2. 4. 8.]
<NDArray 4 @cpu(0)>
x + y 
[ 3.  4.  6. 10.]
<NDArray 4 @cpu(0)>
x - y 
[-1.  0.  2.  6.]
<NDArray 4 @cpu(0)>
x*y 
[ 2.  4.  8. 16.]
<NDArray 4 @cpu(0)>
x / y 
[0.5 1.  2.  4. ]
<NDArray 4 @cpu(0)>


In [ ]:
"""

In addition to other operations we can also perform matrix operations. In the following code snippet we will 
perform matrix multiplication of x and transpose of y.


"""

In [31]:
x=nd.arange(12).reshape((3, 4))
y=nd.array([[2,1,4,3], [1,2,3,4], [4,3,2,1]])
nd.dot(x, y.T)  #Dot product between x and y_transpose...adding a .T does the transpose trick


[[ 18.  20.  10.]
 [ 58.  60.  50.]
 [ 98. 100.  90.]]
<NDArray 3x3 @cpu(0)>

In [34]:
nd.concat(x, y, dim=0)


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [ 2.  1.  4.  3.]
 [ 1.  2.  3.  4.]
 [ 4.  3.  2.  1.]]
<NDArray 6x4 @cpu(0)>