## Linear algebra experiments in this notebook...

In [1]:
#Author-Vishal Burman

In [2]:
from mxnet import nd

## Scalars

In [3]:
#We can work with Scalars in mxnet with ndArray with one element

In [4]:
x=nd.array([3])
y=nd.array([2])

In [5]:
print("x+y=", x+y)
print("x-y=", x- y)
print("x*y=", x*y)
print("x/y=", x/y)

x+y= 
[5.]
<NDArray 1 @cpu(0)>
x-y= 
[1.]
<NDArray 1 @cpu(0)>
x*y= 
[6.]
<NDArray 1 @cpu(0)>
x/y= 
[1.5]
<NDArray 1 @cpu(0)>


In [ ]:
#Convert the NDArray to python float using the asscalar() method

In [6]:
x.asscalar()

3.0

## Vectors

In [8]:
#We can simply think of vector as a list of numbers...each of the numbers in the list represent a single scalar value

In [9]:
#Put simply vectors are 1D NDArray in MXNet

In [10]:
x=nd.arange(12)
print("x=", x)

x= 
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>


## Length, Dimensionality and Shape

In [11]:
x.shape

(12,)

In [12]:
a=2
x=nd.array([1, 2, 3])
y=nd.array([10, 20, 30])
print(a*x)
print(a*x+y)


[2. 4. 6.]
<NDArray 3 @cpu(0)>

[12. 24. 36.]
<NDArray 3 @cpu(0)>


## Matrices

In [13]:
#Just as vectors generalize scalars from 0 to 1...matrices generalize vectors from 1D to 2D

In [14]:
A=nd.arange(20).reshape(5, 4)
print(A)


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]
 [16. 17. 18. 19.]]
<NDArray 5x4 @cpu(0)>


In [15]:
#The transpose of the matrix can be found out by:
print(A.T)


[[ 0.  4.  8. 12. 16.]
 [ 1.  5.  9. 13. 17.]
 [ 2.  6. 10. 14. 18.]
 [ 3.  7. 11. 15. 19.]]
<NDArray 4x5 @cpu(0)>


## Tensors

In [16]:
#Tensors give us a generic way of discussing arrays with arbitrary number of axes

In [17]:
x=nd.arange(24).reshape(2, 3, 4)

In [18]:
x


[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]

 [[12. 13. 14. 15.]
  [16. 17. 18. 19.]
  [20. 21. 22. 23.]]]
<NDArray 2x3x4 @cpu(0)>

## Basic properties of tensor arithmetic

In [22]:
a=2
X=nd.ones(3)
Y=nd.zeros(3)
print(X.shape)
print(Y.shape)
print((a*X).shape)
print((a*X+y).shape)

(3,)
(3,)
(3,)
(3,)


## Sums and Means

In [24]:
print(X)
print(X.sum())


[1. 1. 1.]
<NDArray 3 @cpu(0)>

[3.]
<NDArray 1 @cpu(0)>


In [26]:
#Lets define a multi-dimensional tensor

In [27]:
a=nd.arange(120).reshape(2, 3, 4, 5)

In [30]:
print(a)


[[[[  0.   1.   2.   3.   4.]
   [  5.   6.   7.   8.   9.]
   [ 10.  11.  12.  13.  14.]
   [ 15.  16.  17.  18.  19.]]

  [[ 20.  21.  22.  23.  24.]
   [ 25.  26.  27.  28.  29.]
   [ 30.  31.  32.  33.  34.]
   [ 35.  36.  37.  38.  39.]]

  [[ 40.  41.  42.  43.  44.]
   [ 45.  46.  47.  48.  49.]
   [ 50.  51.  52.  53.  54.]
   [ 55.  56.  57.  58.  59.]]]


 [[[ 60.  61.  62.  63.  64.]
   [ 65.  66.  67.  68.  69.]
   [ 70.  71.  72.  73.  74.]
   [ 75.  76.  77.  78.  79.]]

  [[ 80.  81.  82.  83.  84.]
   [ 85.  86.  87.  88.  89.]
   [ 90.  91.  92.  93.  94.]
   [ 95.  96.  97.  98.  99.]]

  [[100. 101. 102. 103. 104.]
   [105. 106. 107. 108. 109.]
   [110. 111. 112. 113. 114.]
   [115. 116. 117. 118. 119.]]]]
<NDArray 2x3x4x5 @cpu(0)>


In [31]:
#To get the element-wise sum of elements
print(nd.sum(a))


[7140.]
<NDArray 1 @cpu(0)>


In [32]:
#Now to calculate the mean of the above tensor

In [33]:
print(a.mean())


[59.5]
<NDArray 1 @cpu(0)>


In [34]:
#To calculate the mean using the formula

In [35]:
print(nd.sum(a)/a.size)


[59.5]
<NDArray 1 @cpu(0)>


In [41]:
print(a.size)

120


## Dot Product

In [42]:
x=nd.arange(4)
y=nd.ones(4)
print(x, y, nd.dot(x, y))


[0. 1. 2. 3.]
<NDArray 4 @cpu(0)> 
[1. 1. 1. 1.]
<NDArray 4 @cpu(0)> 
[6.]
<NDArray 1 @cpu(0)>


In [ ]:
#By using the traditional formula

In [43]:
nd.sum(x*y)


[6.]
<NDArray 1 @cpu(0)>

## Matrix-vector products

In [44]:
A, x

(
 [[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]
  [12. 13. 14. 15.]
  [16. 17. 18. 19.]]
 <NDArray 5x4 @cpu(0)>, 
 [0. 1. 2. 3.]
 <NDArray 4 @cpu(0)>)

In [47]:
print(A.shape, x.shape)

(5, 4) (4,)


In [50]:
#We can do the matix-vector multiplication using the same old dot product

In [51]:
nd.dot(A, x)


[ 14.  38.  62.  86. 110.]
<NDArray 5 @cpu(0)>

## Matrix-Matrix multiplication

In [52]:
A


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]
 [16. 17. 18. 19.]]
<NDArray 5x4 @cpu(0)>

In [53]:
A.shape

(5, 4)

In [54]:
B=nd.ones(12).reshape(4, -1)
B


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
<NDArray 4x3 @cpu(0)>

In [ ]:
# We can do the matrix-matrix multiplication using the nd.dot(...) yet again

In [55]:
nd.dot(A, B)


[[ 6.  6.  6.]
 [22. 22. 22.]
 [38. 38. 38.]
 [54. 54. 54.]
 [70. 70. 70.]]
<NDArray 5x3 @cpu(0)>

## Norms

In [56]:
x


[0. 1. 2. 3.]
<NDArray 4 @cpu(0)>

In [57]:
nd.norm(x)


[3.7416573]
<NDArray 1 @cpu(0)>

In [58]:
#The above calculates the l2 norm

In [59]:
# To calculate the l1 norm we calculate by formula-based method

In [60]:
nd.sum(nd.abs(x))


[6.]
<NDArray 1 @cpu(0)>

In [61]:
#l1 norm takes the sum of the absolute values of the elements