In [1]:
#Author-Vishal Burman

In [2]:
from mxnet import nd

In [ ]:
#We create a vector of size 12

In [4]:
x=nd.arange(12)
print(x)


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>


In [5]:
#The shape of the vector

In [6]:
x.shape

(12,)

In [7]:
#x.reshape function does the same thing...

In [10]:
x.size

12

In [11]:
#Reshape as the name suggests can reshape size of one vetor into another size

In [12]:
x.reshape(4,3)


[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]
<NDArray 4x3 @cpu(0)>

In [15]:
#trick comes in handy...-1 can reshape the other column and we dont have to calculate

In [16]:
x.reshape((4, -1))


[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]
<NDArray 4x3 @cpu(0)>

In [17]:
x.reshape((3, -1))


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [18]:
#The empty method just grabs some memory and hands back a matrix without setting the values of any of the entries


In [19]:
nd.empty((3, 4))


[[0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00]
 [0.000000e+00 0.000000e+00 2.135579e-42 0.000000e+00]
 [0.000000e+00 9.275518e-39 0.000000e+00 1.019374e-38]]
<NDArray 3x4 @cpu(0)>

In [20]:
#The above is very efficient but we generally want our entries with zeros or values from normally sampled values

In [ ]:
#The zeros method creates a tensor with initial values of 0

In [22]:
nd.zeros((3, 4, 2))


[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]
<NDArray 3x4x2 @cpu(0)>

In [23]:
#The ones method creates a tensor with initial values of 1

In [24]:
nd.ones((3, 4))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

In [25]:
#we can also specify each element in the tensor

In [27]:
nd.array(([1, 2, 3], [4, 5, 6], [7, 8, 9]))


[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
<NDArray 3x3 @cpu(0)>

In [28]:
#Some cases require to randomly sample the values according to some known probablity distribution

In [29]:
nd.random.normal(0,1, shape=(3, 4))


[[ 1.1630785   0.4838046   0.29956347  0.15302546]
 [-1.1688148   1.5580711  -0.5459446  -2.3556297 ]
 [ 0.5414402   2.6785066   1.2546345  -0.54877394]]
<NDArray 3x4 @cpu(0)>

In [30]:
#The above has zero mean and unit variance

In [31]:
##Operations

In [32]:
#In MXNet the operations line + - * and / have been lifted to element wise functions

In [33]:
x=nd.array([1, 2, 3, 4])
x


[1. 2. 3. 4.]
<NDArray 4 @cpu(0)>

In [35]:
y=nd.ones_like(x)
y


[1. 1. 1. 1.]
<NDArray 4 @cpu(0)>

In [37]:
y=y*2

In [38]:
y


[2. 2. 2. 2.]
<NDArray 4 @cpu(0)>

In [39]:
#Every element is multiplied by 2

In [40]:
print(x+y)


[3. 4. 5. 6.]
<NDArray 4 @cpu(0)>


In [41]:
print(x*y)


[2. 4. 6. 8.]
<NDArray 4 @cpu(0)>


In [42]:
print(x**y)


[ 1.  4.  9. 16.]
<NDArray 4 @cpu(0)>


In [43]:
#Exponentiation can also be applied element-wise

In [44]:
x.exp()


[ 2.7182817  7.389056  20.085537  54.59815  ]
<NDArray 4 @cpu(0)>

In [3]:
#In addition to the above opeartions we can also peform matrix operations

In [10]:
x=nd.arange(12).reshape((3,4))
y=nd.array([[1, 2, 3, 4], [4,5, 6, 7], [8, 9, 10, 11]])

In [12]:
nd.dot(x, y.T)


[[ 20.  38.  62.]
 [ 60. 126. 214.]
 [100. 214. 366.]]
<NDArray 3x3 @cpu(0)>

In [13]:
#We can also merge the above two ndArrays along any dimensions

In [14]:
x


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [15]:
y


[[ 1.  2.  3.  4.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [19]:
nd.concat(x, y, dim=0) # Concatinating the above two tensors along dimension 0 in rows


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [ 1.  2.  3.  4.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 6x4 @cpu(0)>

In [18]:
nd.concat(x, y, dim=1) #Concatinating the two tensors along dimensions 1 in columns


[[ 0.  1.  2.  3.  1.  2.  3.  4.]
 [ 4.  5.  6.  7.  4.  5.  6.  7.]
 [ 8.  9. 10. 11.  8.  9. 10. 11.]]
<NDArray 3x8 @cpu(0)>

In [20]:
#We can also construct the NDarrays via logical statements 

In [21]:
x==y


[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

In [22]:
#To find the sum of all the elements of the ndArray

In [23]:
x.sum()


[66.]
<NDArray 1 @cpu(0)>

In [24]:
#To transform the result into scalar

In [25]:
x.sum().asscalar()

66.0

In [26]:
#We can also take the l2 norm using the following method

In [27]:
x.norm().asscalar()

22.494442

## Broadcast Mechanisms

In [28]:
#Define two matrices

In [36]:
x=nd.arange(3).reshape((3, 1))

In [38]:
y=nd.arange(2).reshape(1,2)

In [40]:
x, y

(
 [[0.]
  [1.]
  [2.]]
 <NDArray 3x1 @cpu(0)>, 
 [[0. 1.]]
 <NDArray 1x2 @cpu(0)>)

In [41]:
x+y


[[0. 1.]
 [1. 2.]
 [2. 3.]]
<NDArray 3x2 @cpu(0)>

In [42]:
#The shape of the matrices were (3,1) and (1, 2) but the shapes do not match up...braodcasting helps in these cases

## Indexing and Slicing

In [44]:
x=nd.arange(3).reshape((3, 1))

In [45]:
x[1:3] #Define the range of indexing the elements


[[1.]
 [2.]]
<NDArray 2x1 @cpu(0)>

In [48]:
x[1, 0] #Define the exact row and column of the element


[1.]
<NDArray 1 @cpu(0)>

In [53]:
x[0:3, :] #Define the particular ranges of both row and column


[[0.]
 [1.]
 [2.]]
<NDArray 3x1 @cpu(0)>

## Saving Memory

In [54]:
before=id(y)

In [55]:
y=x+y
id(y)==before

False

In [56]:
#The above shows the reference pointer of y was pointing to another
#location at the beginning and calculation of x+y
#it points to the location storing x+y
#Unnecessary memory allocation!

In [57]:
# We dont want any unnecessary memory allocation :
#1. Unnecessary memory allocation means unnecessary memory usage
#2. The chance of memory leakage

In [58]:
#For in place memory operations:
z=y.zeros_like()

In [59]:
print("id(z)", id(z))
z[:]=x+y
print("id(z)", id(z))

id(z) 2176587938952
id(z) 2176587938952


In [60]:
#The above does look pretty but still the result of x+y is stored in another memory buffer

In [ ]:
#To counter the redundant buffer we use the following technique

In [68]:
x1=nd.arange(12).reshape(3, 4)

In [69]:
x2=nd.arange(12).reshape(3, 4)

In [73]:
z1=x1.zeros_like()
before=id(z1)
nd.elemwise_add(x1, x2, out=z1)
id(z1)==before

True

In [74]:
#If the value of x is not used in subsequent operations we can reduce the memory head:

In [75]:
before=id(x1)
x1+=x2
id(x1)==before

True

## Mutual Transformation of NDArray and NumPy

In [ ]:
#We we convert the MXNet ndArray to numPy array to and fro...they dont share the same chunk of memory

In [76]:
import numpy as np

In [77]:
a=x1.asnumpy()
print(type(a))
b=nd.array(a)
print(type(b))

<class 'numpy.ndarray'>
<class 'mxnet.ndarray.ndarray.NDArray'>
